apiVersion: v1
kind: Service

metadata:
  name: prestashop-db-service-headless

spec:
  clusterIP: None

  selector:
    app: prestashop-db

  ports:
    - name: mysql
      port: {{ .Values.prestashopDatabase.service.port }}
      targetPort: {{ .Values.prestashopDatabase.service.port }}
      protocol: TCP

