apiVersion: v1
kind: ConfigMap

metadata:
  name: prestashop-configmap

data:
  PUBLIC_HOST: {{ .Values.prestashop.publicHost | quote }}
  NGINX_NODE_PORT: {{ .Values.nginx.service.nodePort | quote }}