apiVersion: v1
kind: Service

metadata:
  name: wordpress-db-service-headless

spec:
  clusterIP: None

  selector:
    app: wordpress-db

  ports:
    - name: mysql
      port: {{ .Values.wordpressDatabase.service.port }}
      targetPort: {{ .Values.wordpressDatabase.service.port }}
      protocol: TCP

