apiVersion: v1
kind: Service

metadata:
  name: wordpress-app-service

spec:
  type: {{ .Values.wordpress.service.type }}

  selector:
    app: wordpress-app

  ports:
    - name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: http
      protocol: TCP

