{
 "title": "Liora Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_status_ready{\r\n    namespace=\"$namespace\",\r\n    condition=\"true\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  kube_pod_info{\r\n    namespace=\"$namespace\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarts - last 15m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    kube_pod_container_status_restarts_total{\r\n      namespace=\"$namespace\"\r\n    }[15m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_deployment_status_replicas_available{\r\n    namespace=\"$namespace\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready StatefulSet Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_statefulset_status_replicas_ready{\r\n    namespace=\"$namespace\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_persistentvolumeclaim_status_phase{\r\n    namespace=\"$namespace\",\r\n    phase=\"Bound\"\r\n  }\r\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"$namespace\",\r\n      container!=\"\",\r\n      container!=\"POD\",\r\n      image!=\"\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    container!=\"\",\r\n    container!=\"POD\",\r\n    image!=\"\"\r\n  }\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WordPress Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\r\n  liora_namespace=\"$namespace\",\r\n  application=\"wordpress\"\r\n} or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\r\n  liora_namespace=\"$namespace\",\r\n  application=\"nginx\"\r\n} or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PrestaShop Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{\r\n  liora_namespace=\"$namespace\",\r\n  application=\"prestashop\"\r\n} or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}