server {
    listen 80;

    absolute_redirect off;
    
    location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
}

    location = /wordpress {
        return 301 /wordpress/;
    }

    location /wordpress/ {
        proxy_pass http://wordpress/;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /prestashop {
        return 301 /prestashop/;
    }

    location /prestashop/ {
        proxy_pass http://prestashop/;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}