server {
    listen 80;

    location /wordpress/ {
        proxy_pass http://wordpress/;
        proxy_set_header Host localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host localhost:8080;
        proxy_set_header X-Forwarded-Port 8080;
        proxy_set_header X-Forwarded-Proto http;
    }

    location /prestashop/ {
        proxy_pass http://prestashop/;
        proxy_set_header Host localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host localhost:8080;
        proxy_set_header X-Forwarded-Port 8080;
        proxy_set_header X-Forwarded-Proto http;
    }

    location / {
        return 200 "NGINX reverse proxy is running.\nUse /wordpress/ or /prestashop/\n";
    }
}