
name: liora-webservices-dev
services:
  nginx:
    build:
      context: ./nginx
    image: liora-nginx-proxy:dev
    ports:
      - "8080:80"
    depends_on:
      - wordpress
      - prestashop
    networks:
      - liora-dev-proxy-network
    restart: on-failure:3

  wordpress-db:
    build:
      context: ./wordpress-db
    image: liora-wordpress-db:dev
    environment:
      MARIADB_DATABASE: wordpress_dev
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - liora-dev-wordpress-db-data:/var/lib/mysql
    networks:
      - liora-dev-wordpress-network #maybe one network?
    restart: on-failure:2
  
  wordpress:
    build:
      context: ./wordpress
    image: liora-wordpress:dev
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306 
      WORDPRESS_DB_NAME: wordpress_dev
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: | 
        define('WP_HOME', 'http://localhost:8080/wordpress');
        define('WP_SITEURL', 'http://localhost:8080/wordpress');
    depends_on:
      - wordpress-db
    volumes:
      - liora-dev-wordpress-files:/var/www/html
    networks:
      - liora-dev-proxy-network
      - liora-dev-wordpress-network
    restart: on-failure:2
    
  prestashop-db:
    build:
      context: ./prestashop-db
    image: liora-prestashop-db:dev
    environment:
      MYSQL_DATABASE: prestashop_dev
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - liora-dev-prestashop-db-data:/var/lib/mysql
    networks:
      - liora-dev-prestashop-network
    restart: on-failure:2

  prestashop:
    build:
      context: ./prestashop
    image: liora-prestashop:dev
    environment:
      DB_SERVER: prestashop-db
      DB_NAME: prestashop_dev
      DB_USER: prestashop
      DB_PASSWD: prestashop
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
    depends_on:
      - prestashop-db
    volumes:
      - liora-dev-prestashop-files:/var/www/html
    networks:
      - liora-dev-proxy-network
      - liora-dev-prestashop-network
    restart: on-failure:2

volumes:
    liora-dev-wordpress-db-data:
    liora-dev-wordpress-files:
    liora-dev-prestashop-db-data:
    liora-dev-prestashop-files:
    
networks:
    liora-dev-proxy-network:
      driver: bridge
      
    liora-dev-wordpress-network:
      driver: bridge
      
    liora-dev-prestashop-network:
      driver: bridge