apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: prestashop-db
  namespace: liora-dev

spec:
  serviceName: prestashop-db-service-headless
  replicas: 1

  selector:
    matchLabels:
      app: prestashop-db

  template:
    metadata:
      labels:
        app: prestashop-db

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          ports:
            - name: mysql
              containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: liora-db-secrets
                  key: PRESTASHOP_DB_NAME

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: liora-db-secrets
                  key: PRESTASHOP_DB_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: liora-db-secrets
                  key: PRESTASHOP_DB_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: liora-db-secrets
                  key: PRESTASHOP_DB_ROOT_PASSWORD

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          volumeMounts:
            - name: prestashop-db-data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: prestashop-db-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi