apiVersion: v1
kind: Service

metadata:
  name: wordpress-app-service
  namespace: liora-dev

spec:
  type: ClusterIP

  selector:
    app: wordpress-app
    
  ports:
    - name: http
      port: 80
      targetPort: 80